---
title: "Ukraine maps for manipulation estimates"
output: html_notebook
---

```{r setup}
library(rgdal)
library(sp)
library(ggplot2)
library(tidyverse)
shape.ukr <- readOGR(dsn = "C:/Users/Cole/Documents/Research projects/ukraine_analysis_2020", layer = "ukr_admbnda_adm1_q2_sspe_20171221")
ukr.data <- read.csv("Ukraine main dataset.csv")
ukrmap.data <- fortify(shape.ukr, region = "ADM1_PCODE")
```



```{r}

ggplot(ukrmap.data, aes(x = long, y = lat, group = group)) + geom_polygon(fill = "white", color = "lightgray")
```


```{r}
ukr.data.2002 <- subset(ukr.data, ukr.data$year == 2002)
combined.data <- left_join(ukr.data.2002, ukrmap.data, by = "id")

p.ukr.2002 <- ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.48, 1.04), colors = hcl.colors(n = 10)) +
  labs(x = NULL, y = NULL, title = "Pro-eastern turnout coefficients, 2002", fill = "Turnout \ncoefficient") + theme_bw()
p.ukr.2002
```


```{r}
ukr.data.2004 <- subset(ukr.data, ukr.data$year == 2004)
combined.data <- left_join(ukr.data.2004, ukrmap.data, by = "id")

p.ukr.2004 <- ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.49, 1.01), colors = hcl.colors(n = 10))+
  labs(x = NULL, y = NULL, title = "Pro-eastern turnout coefficients, 2004", fill = "Turnout \ncoefficient") + theme_bw()
p.ukr.2004
```

```{r}
ukr.data.2006 <- subset(ukr.data, ukr.data$year == 2006)
combined.data <- left_join(ukr.data.2006, ukrmap.data, by = "id")

p.ukr.2006 <- ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.49, 1.01), colors = hcl.colors(n = 10))+
  labs(x = NULL, y = NULL, title = "Pro-eastern turnout coefficients, 2006", fill = "Turnout \ncoefficient") + theme_bw()
p.ukr.2006
```



```{r}
ukr.data.2010_2 <- subset(ukr.data, ukr.data$year == 2010 & ukr.data$round.2 == 1)
combined.data <- left_join(ukr.data.2010_2, ukrmap.data, by = "id")

ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.07,.9), colors = hcl.colors(n = 10))
```


```{r}
ukr.data.2012 <- subset(ukr.data, ukr.data$year == 2012)
combined.data <- left_join(ukr.data.2012, ukrmap.data, by = "id")

p.ukr.2012 <- ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.07,.9), colors = hcl.colors(n = 10))+
  labs(x = NULL, y = NULL, title = "Pro-eastern turnout coefficients, 2012", fill = "Turnout \ncoefficient") + theme_bw()
p.ukr.2012
```


```{r}
ukr.data.2014 <- subset(ukr.data, ukr.data$year == 2014 & ukr.data$presidential == 1)
combined.data <- left_join(ukr.data.2014, ukrmap.data, by = "id")

p.ukr.2014 <- ggplot(combined.data, aes(long, lat, group = group))+
  geom_polygon(aes(fill = coefs.east ), color = "white")+
  scale_fill_gradientn(limits = c(-0.07,.9), colors = hcl.colors(n = 10))+
  labs(x = NULL, y = NULL, title = "Pro-eastern turnout coefficients, 2014", fill = "Turnout \ncoefficient") + theme_bw()
p.ukr.2014
```


```{r}
png("ukraine map 2002.png", height=5,
    width=7, units="in", res=600)
p.ukr.2002
dev.off()

png("ukraine map 2004.png", height=5,
    width=7, units="in", res=600)
p.ukr.2004
dev.off()

png("ukraine map 2006.png", height=5,
    width=7, units="in", res=600)
p.ukr.2006
dev.off()

png("ukraine map 2012.png", height=5,
    width=7, units="in", res=600)
p.ukr.2012
dev.off()

png("ukraine map 2014.png", height=5,
    width=7, units="in", res=600)
p.ukr.2014
dev.off()
```



